version: "3.8"
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    environment:
      AZURE_CONNECTION_STRING: ${AZURE_CONNECTION_STRING}
    image: meet58.azurecr.io/airflowimage
    container_name: Hotel-Review-Sentiment-Classification-airflow
    ports:
      - "8080:8080"

  streamlitapp:
    build:
      context: ./
      dockerfile: Dockerfile.streamlit
    image: meet58.azurecr.io/streamlitimage
    container_name: Hotel-Review-Sentiment-Classification-streamlit
    ports:
      - "8051:8051"