stages:
  training:
    cmd: python src/pipeline/Complete_Pipeline.py
    deps:
      - src/components/data_ingestion.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py
      - src/components/model_evaluation.py
    outs:
      - artifacts/hotel_reviews.csv