# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Pipeline-Automation-with-Airflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://meet58.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4d32e8a44d2541909b7ced57e206f15a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d8dc26673e0649908a17ee720c67eebe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: meet58.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d32e8a44d2541909b7ced57e206f15a }}/airflowimage:${{ github.sha }}
        file: ./Dockerfile.airflow

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Pipeline-Automation-with-Airflow'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7fa8fef1d4fd4df2a37b27eae9cd0d24 }}
        images: 'meet58.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4d32e8a44d2541909b7ced57e206f15a }}/airflowimage:${{ github.sha }}'
