# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Hotel-Review-Sentiment-Classification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://meet58.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_27caa021a67c4b44a31f1e67d67b9d4a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2845acb739e848a5a726e223980d507e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: meet58.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_27caa021a67c4b44a31f1e67d67b9d4a }}/streamlitimage:${{ github.sha }}
        file: ./Dockerfile.streamlit

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Hotel-Review-Sentiment-Classification'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7756f4e7d64d4bd7ac011282327ce227 }}
        images: 'meet58.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_27caa021a67c4b44a31f1e67d67b9d4a }}/streamlitimage:${{ github.sha }}'
